version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: claims_postgres
    ports:
      - "5402:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: claims_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: claims_backend
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=claims_db

  employee-claims:
    build: ./Employee-claims
    container_name: employee_claims_ui
    ports:
      - "9075:80"
    depends_on:
      - backend

  hr-claims:
    build: ./HR-claims
    container_name: hr_claims_ui
    ports:
      - "9076:80"
    depends_on:
      - backend

volumes:
  pgdata:

